all:test helloword stopwatch

test:test.cpp
	g++ test.cpp -o test 

helloword:helloword.cpp
	g++ helloword.cpp -o helloword

stopwatch:stopwatch.cpp
	g++ stopwatch.cpp -o stopwatch

clean:
	rm -fr test helloword stopwatch
